-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.pvr_audit_log
(
    audit_id_pk bigint NOT NULL,
    section character varying(100) NOT NULL,
    action text NOT NULL,
    request character varying(200) NOT NULL,
    comment character varying(200) NOT NULL,
    ip_addr character varying(20) NOT NULL,
    login_id_fk bigint NOT NULL,
    "timestamp" time without time zone NOT NULL,
    PRIMARY KEY (audit_id_pk)
);

CREATE TABLE public.pvr_candidate_details
(
    candidate_id_pk bigint NOT NULL,
    reference_no_fk bigint NOT NULL,
    employer_id_fk bigint NOT NULL,
    profile_id_fk bigint NOT NULL,
    candidate_f_name character varying(50) NOT NULL,
    candidate_m_name character varying(50) NOT NULL,
    candidate_l_name character varying(50) NOT NULL,
    candidate_gender_id_fk bigint NOT NULL,
    candidate_caste_id_fk bigint NOT NULL,
    candidate_aadhaar_no numeric(12, 0) NOT NULL,
    candidate_house_no1 character varying(50) NOT NULL,
    candidate_street1 character varying(50) NOT NULL,
    candidate_landmark1 character varying(50) NOT NULL,
    candidate_city1 character varying NOT NULL,
    candidate_post_office1 character varying NOT NULL,
    candidate_police_station_id1_fk bigint NOT NULL,
    candidate_pin1_fk bigint NOT NULL,
    candidate_district_id1_fk bigint NOT NULL,
    candidate_photo_path character varying(80) NOT NULL,
    candidate_defence_type_id_fk bigint NOT NULL,
    candidate_house_no2 character varying NOT NULL,
    candidate_street2 character varying NOT NULL,
    candidate_landmark2 character varying NOT NULL,
    candidate_city2 character varying NOT NULL,
    candidate_post_office2 character varying NOT NULL,
    candidate_police_station_id2_fk bigint NOT NULL,
    candidate_pin2_fk bigint NOT NULL,
    candidate_district_id2_fk bigint NOT NULL,
    PRIMARY KEY (candidate_id_pk)
);

CREATE TABLE public.pvr_candidate_profile
(
    profile_id_pk bigint NOT NULL,
    candidate_father_name character varying(50) NOT NULL,
    candidate_mother_name character varying(50) NOT NULL,
    candidate_nationality character varying(50) NOT NULL,
    candidate_dob date NOT NULL,
    "candidate_school name" character varying(80) NOT NULL,
    candidate_school_address character varying(100) NOT NULL,
    candidate_school_district_id_fk bigint NOT NULL,
    "candidate_college name " character varying(50) NOT NULL,
    candidate_college_address character varying(100) NOT NULL,
    candidate_college_district_id_fk bigint NOT NULL,
    blood_group character varying NOT NULL,
    PRIMARY KEY (profile_id_pk)
);

CREATE TABLE public.pvr_check_first_user
(
    user_id_pk bigint NOT NULL,
    check_if_first_user integer NOT NULL,
    check_profile_updated_once integer NOT NULL,
    PRIMARY KEY (user_id_pk)
);

CREATE TABLE public.pvr_employer
(
    employer_id_pk bigint NOT NULL,
    profile_id_fk bigint NOT NULL,
    employer_name character varying(50) NOT NULL,
    employer_add1 character varying(50) NOT NULL,
    employer_add2 character varying(50) NOT NULL,
    PRIMARY KEY (employer_id_pk)
);

CREATE TABLE public.pvr_employer_profile
(
    profile_id_pk bigint NOT NULL,
    employer_district_id_fk bigint NOT NULL,
    employer_pincode_fk bigint NOT NULL,
    employer_type_id_fk bigint NOT NULL,
    employer_sender_name character varying(50) NOT NULL,
    employer_sender_designation character varying(50) NOT NULL,
    employer_email character varying(50) NOT NULL,
    employer_contact character varying(50) NOT NULL,
    PRIMARY KEY (profile_id_pk)
);

CREATE TABLE public.pvr_final_status
(
    pvr_final_status_id_pk bigint NOT NULL,
    pvr_id_fk bigint NOT NULL,
    final_status_name character varying(50) NOT NULL,
    PRIMARY KEY (pvr_final_status_id_pk)
);

CREATE TABLE public.pvr_issues
(
    issue_id_pk bigint NOT NULL,
    name "char" NOT NULL,
    email "char" NOT NULL,
    rating numeric NOT NULL,
    description text NOT NULL,
    timstamp timestamp without time zone NOT NULL,
    login_id_fk bigint NOT NULL,
    PRIMARY KEY (issue_id_pk)
);

CREATE TABLE public.pvr_login
(
    username character varying(50) NOT NULL,
    password text NOT NULL,
    user_type_id_fk bigint NOT NULL,
    location_code character varying(12) NOT NULL,
    login_id_pk bigint NOT NULL,
    active_status numeric NOT NULL,
    dept_id_fk bigint NOT NULL,
    office_id_fk bigint NOT NULL,
    desig_id_fk bigint NOT NULL,
    PRIMARY KEY (login_id_pk)
);

CREATE TABLE public.pvr_master_caste
(
    caste_id_pk bigint NOT NULL,
    caste_name character varying(50) NOT NULL,
    PRIMARY KEY (caste_id_pk)
);

CREATE TABLE public.pvr_master_defence
(
    "df_type_id_pk " bigint NOT NULL,
    df_type character varying(50) NOT NULL,
    PRIMARY KEY ("df_type_id_pk ")
);

CREATE TABLE public.pvr_master_department
(
    dept_id_pk bigint NOT NULL,
    dept_name character varying(50) NOT NULL,
    short_name character varying(15) NOT NULL,
    office_id_fk bigint NOT NULL,
    PRIMARY KEY (dept_id_pk)
);

CREATE TABLE public.pvr_master_designation
(
    desig_id_pk bigint NOT NULL,
    desig_name character varying(50) NOT NULL,
    dept_id_fk bigint NOT NULL,
    PRIMARY KEY (desig_id_pk)
);

CREATE TABLE public.pvr_master_district
(
    district_id_pk bigint NOT NULL,
    district_name character varying(50) NOT NULL,
    state_id_fk bigint NOT NULL,
    dist_lg_code bigint NOT NULL,
    PRIMARY KEY (district_id_pk)
);

CREATE TABLE public.pvr_master_employer_type
(
    type_id_pk bigint NOT NULL,
    type_name character varying(50) NOT NULL,
    PRIMARY KEY (type_id_pk)
);

CREATE TABLE public.pvr_master_gender
(
    gender_id_pk bigint NOT NULL,
    gender_name character varying(20) NOT NULL,
    PRIMARY KEY (gender_id_pk)
);

CREATE TABLE public.pvr_master_office
(
    office_id_pk bigint NOT NULL,
    office_name character varying(50) NOT NULL,
    district_id_fk bigint NOT NULL,
    PRIMARY KEY (office_id_pk)
);

CREATE TABLE public.pvr_master_pincode
(
    pincode_id_pk bigint NOT NULL,
    pincode_no_pk bigint NOT NULL,
    district_id_fk bigint NOT NULL,
    PRIMARY KEY (pincode_id_pk)
);

CREATE TABLE public.pvr_master_policestation
(
    ps_id_pk bigint NOT NULL,
    ps_name character varying(50) NOT NULL,
    district_id_fk bigint NOT NULL,
    PRIMARY KEY (ps_id_pk)
);

CREATE TABLE public.pvr_master_state
(
    state_id_pk bigint NOT NULL,
    state_name character varying(50) NOT NULL,
    PRIMARY KEY (state_id_pk)
);

CREATE TABLE public.pvr_memo
(
    memo_id_pk bigint NOT NULL,
    memo_no character varying(50) NOT NULL,
    memo_issued_by_fk bigint NOT NULL,
    issue_date date NOT NULL,
    PRIMARY KEY (memo_id_pk)
);

CREATE TABLE public.pvr_privilege
(
    privilege_id_pk bigint NOT NULL,
    "parent " integer NOT NULL,
    link character varying(70) NOT NULL,
    "order" integer NOT NULL,
    page_name character varying(70) NOT NULL,
    active_status numeric NOT NULL,
    view_sidebar numeric NOT NULL,
    PRIMARY KEY (privilege_id_pk)
);

CREATE TABLE public.pvr_receipt_no
(
    receipt_no bigint NOT NULL,
    receipt_date date NOT NULL,
    PRIMARY KEY (receipt_no)
);

CREATE TABLE public.pvr_reference_no
(
    ref_no_pk bigint NOT NULL,
    receipt_no_fk bigint NOT NULL,
    ref_date date NOT NULL,
    PRIMARY KEY (ref_no_pk)
);

CREATE TABLE public.pvr_report
(
    pvr_report_id_pk bigint NOT NULL,
    ref_no_fk bigint NOT NULL,
    receipt_no_fk bigint NOT NULL,
    pvr_report_no character varying(50) NOT NULL,
    pvr_id_fk bigint NOT NULL,
    issue_date date NOT NULL,
    pvr_report_path character varying(60) NOT NULL,
    PRIMARY KEY (pvr_report_id_pk)
);

CREATE TABLE public.pvr_user_privilege
(
    user_priv_id_pk bigint NOT NULL,
    privilege_id_fk bigint NOT NULL,
    active_status integer NOT NULL,
    user_type_id_fk bigint NOT NULL,
    PRIMARY KEY (user_priv_id_pk)
);

CREATE TABLE public.pvr_user_profile
(
    profile_id_pk bigint NOT NULL,
    username character varying(50) NOT NULL,
    first_name character varying(50) NOT NULL,
    middle_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    mobille numeric(10, 0) NOT NULL,
    "email " character varying(50) NOT NULL,
    district_id_fk bigint NOT NULL,
    designation_id_fk bigint NOT NULL,
    office_id_fk bigint NOT NULL,
    department_id_fk bigint NOT NULL,
    signature_path character varying(100) NOT NULL,
    user_type_id_fk bigint NOT NULL,
    PRIMARY KEY (profile_id_pk)
);

CREATE TABLE public.pvr_user_type
(
    user_type_id_pk bigint NOT NULL,
    designation_id_fk bigint NOT NULL,
    active_status numeric NOT NULL,
    user_level integer NOT NULL,
    PRIMARY KEY (user_type_id_pk)
);

CREATE TABLE public.pvr_vr_detail
(
    pvr_id_pk bigint NOT NULL,
    receipt_no_fk bigint NOT NULL,
    candidate_id_fk bigint NOT NULL,
    application_date date NOT NULL,
    pvr_type_fk bigint NOT NULL,
    pvr_sent_to_id_fk bigint NOT NULL,
    memo_id_fk bigint NOT NULL,
    pvr_with_id_fk bigint NOT NULL,
    pvr_final_status_id_fk bigint NOT NULL,
    remarks text NOT NULL,
    pvr_report_id_fk bigint NOT NULL,
    PRIMARY KEY (pvr_id_pk)
);

CREATE TABLE public.pvr_with
(
    pvr_with_id_pk bigint NOT NULL,
    pvr_id_fk bigint NOT NULL,
    pvr_with_status character varying(50) NOT NULL,
    pvr_with_date date NOT NULL,
    PRIMARY KEY (pvr_with_id_pk)
);

ALTER TABLE public.pvr_audit_log
    ADD FOREIGN KEY (login_id_fk)
    REFERENCES public.pvr_login (login_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (candidate_caste_id_fk)
    REFERENCES public.pvr_master_caste (caste_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (candidate_defence_type_id_fk)
    REFERENCES public.pvr_master_defence ("df_type_id_pk ")
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (candidate_district_id1_fk)
    REFERENCES public.pvr_master_district (district_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (candidate_gender_id_fk)
    REFERENCES public.pvr_master_gender (gender_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (candidate_pin1_fk)
    REFERENCES public.pvr_master_pincode (pincode_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (candidate_police_station_id1_fk)
    REFERENCES public.pvr_master_policestation (ps_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (employer_id_fk)
    REFERENCES public.pvr_employer (employer_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (profile_id_fk)
    REFERENCES public.pvr_candidate_profile (profile_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (reference_no_fk)
    REFERENCES public.pvr_reference_no (ref_no_pk)
    NOT VALID;


ALTER TABLE public.pvr_check_first_user
    ADD FOREIGN KEY (user_id_pk)
    REFERENCES public.pvr_login (login_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_employer
    ADD FOREIGN KEY (profile_id_fk)
    REFERENCES public.pvr_employer_profile (profile_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_employer_profile
    ADD FOREIGN KEY (employer_district_id_fk)
    REFERENCES public.pvr_master_district (district_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_employer_profile
    ADD FOREIGN KEY (employer_pincode_fk)
    REFERENCES public.pvr_master_pincode (pincode_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_employer_profile
    ADD FOREIGN KEY (employer_type_id_fk)
    REFERENCES public.pvr_master_employer_type (type_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_final_status
    ADD FOREIGN KEY (pvr_id_fk)
    REFERENCES public.pvr_vr_detail (pvr_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_issues
    ADD FOREIGN KEY (login_id_fk)
    REFERENCES public.pvr_login (login_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_login
    ADD FOREIGN KEY (dept_id_fk)
    REFERENCES public.pvr_master_department (dept_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_login
    ADD FOREIGN KEY (desig_id_fk)
    REFERENCES public.pvr_master_designation (desig_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_login
    ADD FOREIGN KEY (office_id_fk)
    REFERENCES public.pvr_master_office (office_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_login
    ADD FOREIGN KEY (user_type_id_fk)
    REFERENCES public.pvr_user_type (user_type_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_master_department
    ADD FOREIGN KEY (office_id_fk)
    REFERENCES public.pvr_master_office (office_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_master_designation
    ADD FOREIGN KEY (dept_id_fk)
    REFERENCES public.pvr_master_department (dept_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_master_district
    ADD FOREIGN KEY (state_id_fk)
    REFERENCES public.pvr_master_state (state_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_master_office
    ADD FOREIGN KEY (district_id_fk)
    REFERENCES public.pvr_master_district (district_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_master_pincode
    ADD FOREIGN KEY (district_id_fk)
    REFERENCES public.pvr_master_district (district_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_master_policestation
    ADD FOREIGN KEY (district_id_fk)
    REFERENCES public.pvr_master_district (district_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_memo
    ADD FOREIGN KEY (memo_issued_by_fk)
    REFERENCES public.pvr_user_profile (profile_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_reference_no
    ADD FOREIGN KEY (receipt_no_fk)
    REFERENCES public.pvr_receipt_no (receipt_no)
    NOT VALID;


ALTER TABLE public.pvr_report
    ADD FOREIGN KEY (pvr_id_fk)
    REFERENCES public.pvr_vr_detail (pvr_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_report
    ADD FOREIGN KEY (receipt_no_fk)
    REFERENCES public.pvr_receipt_no (receipt_no)
    NOT VALID;


ALTER TABLE public.pvr_report
    ADD FOREIGN KEY (ref_no_fk)
    REFERENCES public.pvr_reference_no (ref_no_pk)
    NOT VALID;


ALTER TABLE public.pvr_user_privilege
    ADD FOREIGN KEY (privilege_id_fk)
    REFERENCES public.pvr_privilege (privilege_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_user_privilege
    ADD FOREIGN KEY (user_type_id_fk)
    REFERENCES public.pvr_user_type (user_type_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_user_profile
    ADD FOREIGN KEY (department_id_fk)
    REFERENCES public.pvr_master_department (dept_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_user_profile
    ADD FOREIGN KEY (designation_id_fk)
    REFERENCES public.pvr_master_designation (desig_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_user_profile
    ADD FOREIGN KEY (district_id_fk)
    REFERENCES public.pvr_master_district (district_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_user_profile
    ADD FOREIGN KEY (office_id_fk)
    REFERENCES public.pvr_master_office (office_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_user_profile
    ADD FOREIGN KEY (user_type_id_fk)
    REFERENCES public.pvr_user_type (user_type_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_user_type
    ADD FOREIGN KEY (designation_id_fk)
    REFERENCES public.pvr_master_designation (desig_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_vr_detail
    ADD FOREIGN KEY (candidate_id_fk)
    REFERENCES public.pvr_candidate_details (candidate_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_vr_detail
    ADD FOREIGN KEY (memo_id_fk)
    REFERENCES public.pvr_memo (memo_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_vr_detail
    ADD FOREIGN KEY (pvr_final_status_id_fk)
    REFERENCES public.pvr_final_status (pvr_final_status_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_vr_detail
    ADD FOREIGN KEY (pvr_report_id_fk)
    REFERENCES public.pvr_report (pvr_report_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_vr_detail
    ADD FOREIGN KEY (pvr_sent_to_id_fk)
    REFERENCES public.pvr_user_profile (profile_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_vr_detail
    ADD FOREIGN KEY (pvr_type_fk)
    REFERENCES public.pvr_master_defence ("df_type_id_pk ")
    NOT VALID;


ALTER TABLE public.pvr_vr_detail
    ADD FOREIGN KEY (pvr_with_id_fk)
    REFERENCES public.pvr_with (pvr_with_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_vr_detail
    ADD FOREIGN KEY (receipt_no_fk)
    REFERENCES public.pvr_receipt_no (receipt_no)
    NOT VALID;


ALTER TABLE public.pvr_with
    ADD FOREIGN KEY (pvr_id_fk)
    REFERENCES public.pvr_vr_detail (pvr_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (candidate_police_station_id2_fk)
    REFERENCES public.pvr_master_policestation (ps_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (candidate_pin2_fk)
    REFERENCES public.pvr_master_pincode (pincode_id_pk)
    NOT VALID;


ALTER TABLE public.pvr_candidate_details
    ADD FOREIGN KEY (candidate_district_id2_fk)
    REFERENCES public.pvr_master_district (district_id_pk)
    NOT VALID;

END;